#!/usr/bin/env python
# -*- coding: utf-8 -*-
# distrubuted under the GPL GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
# written by n3uromanc3r 2010

import wx
import os

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):

        kwds["style"] = wx.ICONIZE|wx.CAPTION|wx.MINIMIZE|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.button_jpeg_select = wx.Button(self, -1, "Select Jpeg...")
        self.text_ctrl_jpeg_details = wx.TextCtrl(self, -1, "")
        self.button_covertfile_select = wx.Button(self, -1, "Select File to embed...")
        self.text_ctrl_covertfile_details = wx.TextCtrl(self, -1, "")
        self.button_embed = wx.Button(self, -1, "Embed")

        self.__set_properties()
        self.__do_layout()

	self.Bind(wx.EVT_BUTTON, self.onClicked, self.button_embed)
	self.Bind(wx.EVT_BUTTON, self.onClicked2, self.button_jpeg_select)
	self.Bind(wx.EVT_BUTTON, self.onClicked3, self.button_covertfile_select)


    def __set_properties(self):

        self.SetTitle("Stegosaur : Where files go undercover :")
        self.SetSize((420, 160))
        self.SetToolTipString("Stegosaur | Ninja files.")
        self.button_jpeg_select.SetMinSize((172, 28))
        self.text_ctrl_jpeg_details.SetMinSize((210, 27))
        self.button_covertfile_select.SetMinSize((172, 28))
        self.text_ctrl_covertfile_details.SetMinSize((210, 27))
        self.button_embed.SetMinSize((150, 50))


    def __do_layout(self):

        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.button_jpeg_select, 0, wx.ALL|wx.ADJUST_MINSIZE, 10)
        sizer_3.Add(self.text_ctrl_jpeg_details, 0, wx.TOP|wx.BOTTOM|wx.ADJUST_MINSIZE, 10)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_4.Add(self.button_covertfile_select, 0, wx.LEFT|wx.RIGHT|wx.ADJUST_MINSIZE, 10)
        sizer_4.Add(self.text_ctrl_covertfile_details, 0, wx.BOTTOM|wx.ALIGN_RIGHT|wx.ADJUST_MINSIZE, 10)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_2.Add(self.button_embed, 0, wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.SetSize((420, 160))


    def onClicked(self, event):
	cmd="steghide embed -p ninja -cf '%(var1)s' -ef '%(var2)s'"
	cmd = cmd % { 'var1' : fullpathimage, 'var2' : fullpathembed } 
        os.system(cmd)
	os.system('notify-send Stegosaur Finished')


    def onClicked2(self, event):
	self.dirname = ''
	dlg = wx.FileDialog(self, "Choose a jpg image", self.dirname,"", "*.*", wx.OPEN)
	if dlg.ShowModal()==wx.ID_OK:
		self.filename=dlg.GetFilename()
		self.dirname=dlg.GetDirectory()		
		dlg.Destroy()
		workingdirimage = self.dirname
		imagefile = self.filename
		global fullpathimage
		fullpathimage = "%s/%s" % (workingdirimage, imagefile)
		self.text_ctrl_jpeg_details.SetValue( "%s" % (fullpathimage) )

    def onClicked3(self, event):
	self.dirname = ''
	dlg = wx.FileDialog(self, "Choose a file to go undercover", self.dirname,"", "*.*", wx.OPEN)
	if dlg.ShowModal()==wx.ID_OK:
		self.filename=dlg.GetFilename()
		self.dirname=dlg.GetDirectory()		
		dlg.Destroy()
		workingdirfile = self.dirname
		embedfile = self.filename
		global fullpathembed
		fullpathembed = "%s/%s" % (workingdirfile, embedfile)
		self.text_ctrl_covertfile_details.SetValue( "%s" % (fullpathembed) )


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
